# Generated by Django 4.2.5 on 2023-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myauthor',
            name='address',
            field=models.CharField(default='Aranyani, Shop No. Sf 204, 2Nd Floor, Vr Surat, Rundh Village, Dumas Road, Magdalla, Surat, Gujarat', max_length=100),
        ),
        migrations.AlterField(
            model_name='myauthor',
            name='bio',
            field=models.CharField(default="I'm passionate about using my financial expertise to help people reach their financial goals.", max_length=100),
        ),
    ]
